apiVersion: v1
kind: Service
metadata:
  name: analytics-reporting-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: analytics-reporting
  type: ClusterIP
