apiVersion: v1
kind: Service
metadata:
  name: document-generation-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: document-generation
  type: ClusterIP
