apiVersion: v1
kind: Service
metadata:
  name: event-swift-frontend-service
spec:
  selector:
    app: event-swift-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
