apiVersion: v1
kind: Service
metadata:
  name: publicity-promotion-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: publicity-promotion
  type: ClusterIP
