apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-discovery
  template:
    metadata:
      labels:
        app: search-discovery
    spec:
      containers:
      - image: search-discovery:latest
        name: search-discovery
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
