apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-reporting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-reporting
  template:
    metadata:
      labels:
        app: analytics-reporting
    spec:
      containers:
      - image: analytics-reporting:latest
        name: analytics-reporting
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
