apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-generation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: document-generation
  template:
    metadata:
      labels:
        app: document-generation
    spec:
      containers:
      - image: document-generation:latest
        name: document-generation
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
