apiVersion: apps/v1
kind: Deployment
metadata:
  name: publicity-promotion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publicity-promotion
  template:
    metadata:
      labels:
        app: publicity-promotion
    spec:
      containers:
      - image: publicity-promotion:latest
        name: publicity-promotion
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
