apiVersion: v1
kind: Service
metadata:
  name: registration-ticketing-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: registration-ticketing
  type: ClusterIP
